const songs = [
    {
        "id": 1,
        "title": "Aagadu",
        "artists": "Shankar Mahadevan",
        "movie": "Aagadu",
        "language": "telugu",
        "genre": "Mass",
        "year": 2014,
        "cover": "images/telugu/Aagadu.jpg",
        "audio": "musics/telugu/Aagadu.mp3"
    },
    {
        "id": 2,
        "title": "Aamchi Mumbai",
        "artists": "Naveen Madhav, Aalap Raju, Ranjith, Rahul Nambiar",
        "movie": "Businessman",
        "language": "telugu",
        "genre": "Mass",
        "year": 2014,
        "cover": "images/telugu/Aamchi_Mumbai.jpg",
        "audio": "musics/telugu/Aamchi_Mumbai.mp3"
    },
    {
        "id": 3,
        "title": "Aaradugula Bullettu",
        "artists": "Vijay Prakash, M.L.R. Karthikeyan",
        "movie": "Attarintiki Daredi",
        "language": "telugu",
        "genre": "Mass",
        "year": 2013,
        "cover": "images/telugu/Aaradugula_Bullettu.jpg",
        "audio": "musics/telugu/Aaradugula_Bullettu.mp3"
    },
    {
        "id": 4,
        "title": "Aaya Sher",
        "artists": "Addula Jangireddy, Arjun Chandy",
        "movie": "The Paradise",
        "language": "telugu",
        "genre": "Mass",
        "year": 2026,
        "cover": "images/telugu/Aaya_Sher.jpg",
        "audio": "musics/telugu/Aaya_Sher.mp3"
    },
    {
        "id": 5,
        "title": "Ammayi",
        "artists": "Raghav Chaitanya",
        "movie": "Animal",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2023,
        "cover": "images/telugu/Ammayi.jpg",
        "audio": "musics/telugu/Ammayi.mp3"
    },
    {
        "id": 6,
        "title": "Anaganaganaga",
        "artists": "Armaan Malik",
        "movie": "Aravinda Sametha",
        "language": "telugu",
        "genre": "Melody",
        "year": 2018,
        "cover": "images/telugu/Anaganaganaga.jpg",
        "audio": "musics/telugu/Anaganaganaga.mp3"
    },
    {
        "id": 7,
        "title": "Arere Yekkada",
        "artists": "Naresh Iyer, Manisha Eerabathini",
        "movie": "Nenu Local",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2017,
        "cover": "images/telugu/Arere_Yekkada.jpg",
        "audio": "musics/telugu/Arere_Yekkada.mp3"
    },
    {
        "id": 8,
        "title": "Bad Boyz",
        "artists": "Priya Himesh, Geetha Madhuri",
        "movie": "Businessman",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2017,
        "cover": "images/telugu/Bad_Boyz.jpg",
        "audio": "musics/telugu/Bad_Boyz.mp3"
    },
    {
        "id": 9,
        "title": "Bhoochadae",
        "artists": "Rahul Nambiar, Shreya Ghoshal",
        "movie": "Race Gurram",
        "language": "telugu",
        "genre": "Mass",
        "year": 2014,
        "cover": "images/telugu/Bhoochadae.jpg",
        "audio": "musics/telugu/Bhoochadae.mp3"
    },
    {
        "id": 10,
        "title": "Bombhaat",
        "artists": "Rahul Sipligunj, Ramya Behara",
        "movie": "LIE",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2017,
        "cover": "images/telugu/Bombhaat.jpg",
        "audio": "musics/telugu/Bombhaat.mp3"
    },
    {
        "id": 11,
        "title": "Bruce Lee",
        "artists": "Simha, Sameera Bharadwaj",
        "movie": "Bruce Lee: The Fighter",
        "language": "telugu",
        "genre": "Mass",
        "year": 2015,
        "cover": "images/telugu/Bruce_Lee.jpg",
        "audio": "musics/telugu/Bruce_Lee.mp3"
    },
    {
        "id": 12,
        "title": "Butta Bomma",
        "artists": "Armaan Malik",
        "movie": "Ala Vaikunthapurramuloo",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2020,
        "cover": "images/telugu/Butta_Bomma.jpg",
        "audio": "musics/telugu/Butta_Bomma.mp3"
    },
    {
        "id": 13,
        "title": "Chandamama Navve",
        "artists": "Haricharan",
        "movie": "Businessman",
        "language": "telugu",
        "genre": "Melody",
        "year": 2011,
        "cover": "images/telugu/Chandamama_Navve.jpg",
        "audio": "musics/telugu/Chandamama_Navve.mp3"
    },
    {
        "id": 14,
        "title": "Cheppave Chirugali",
        "artists": "Udit Narayan, Sujatha Mohan",
        "movie": "Okkadu",
        "language": "telugu",
        "genre": "Melody",
        "year": 2003,
        "cover": "images/telugu/Cheppave_Chirugali.jpg",
        "audio": "musics/telugu/Cheppave_Chirugali.mp3"
    },
    {
        "id": 15,
        "title": "Choododdu",
        "artists": "Mahalakshmi Iyer, Karthik",
        "movie": "Pokiri",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2006,
        "cover": "images/telugu/Choododdu.jpg",
        "audio": "musics/telugu/Choododdu.mp3"
    },
    {
        "id": 16,
        "title": "Dhivara",
        "artists": "Ramya Behara, Deepu",
        "movie": "Baahubali: The Beginning",
        "language": "telugu",
        "genre": "Epic",
        "year": 2015,
        "cover": "images/telugu/Dhivara.jpg",
        "audio": "musics/telugu/Dhivara.mp3"
    },
    {
        "id": 17,
        "title": "Dosti",
        "artists": "Vedala Hemachandra, M. M. Keeravani",
        "movie": "RRR",
        "language": "telugu",
        "genre": "Friendship",
        "year": 2022,
        "cover": "images/telugu/Dosti.jpg",
        "audio": "musics/telugu/Dosti.mp3"
    },
    {
        "id": 18,
        "title": "Down Down Duppa",
        "artists": "Thaman S, Shruti Haasan",
        "movie": "Race Gurram",
        "language": "telugu",
        "genre": "Mass",
        "year": 2014,
        "cover": "images/telugu/Down_Down_Duppa.jpg",
        "audio": "musics/telugu/Down_Down_Duppa.mp3"
    },
    {
        "id": 19,
        "title": "Evarevaro",
        "artists": "Vishal Mishra",
        "movie": "Animal",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2023,
        "cover": "images/telugu/Evarevaro.jpg",
        "audio": "musics/telugu/Evarevaro.mp3"
    },
    {
        "id": 20,
        "title": "Gaaju Bomma",
        "artists": "Hesham Abdul Wahab",
        "movie": "Hi Nanna",
        "language": "telugu",
        "genre": "Melody",
        "year": 2023,
        "cover": "images/telugu/Gaaju_Bomma.jpg",
        "audio": "musics/telugu/Gaaju_Bomma.mp3"
    },
    {
        "id": 21,
        "title": "Gango Renuka Thalli",
        "artists": "Mahalingam",
        "movie": "Pushpa 2: The Rule",
        "language": "telugu",
        "genre": "Devotional",
        "year": 2024,
        "cover": "images/telugu/Gango_Renuka_Thalli.jpg",
        "audio": "musics/telugu/Gango_Renuka_Thalli.mp3"
    },
    {
        "id": 22,
        "title": "Glassmates",
        "artists": "Rahul Sipligunj, Penchal Das",
        "movie": "Chitralahari",
        "language": "telugu",
        "genre": "Fun",
        "year": 2019,
        "cover": "images/telugu/Glassmates.jpg",
        "audio": "musics/telugu/Glassmates.mp3"
    },
    {
        "id": 23,
        "title": "Globetrotter",
        "artists": "M. M. Keeravaani, Shruti Haasan, Kala Bhairava",
        "movie": "Varanasi",
        "language": "telugu",
        "genre": "Theme",
        "year": 2025,
        "cover": "images/telugu/Globetrotter.jpg",
        "audio": "musics/telugu/Globetrotter.mp3"
    },
    {
        "id": 24,
        "title": "Hulala",
        "artists": "Sweekar Agasthi, Silvia Anisha",
        "movie": "Express Raja",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2015,
        "cover": "images/telugu/Hulala.jpg",
        "audio": "musics/telugu/Hulala.mp3"
    },
    {
        "id": 25,
        "title": "Irumudi Kattu",
        "artists": "G. V. Prakash, Ananthu, Kalyan Chakravarthy",
        "movie": "Irumudi",
        "language": "telugu",
        "genre": "Devotional",
        "year": 2026,
        "cover": "images/telugu/Irumudi_Kattu.jpg",
        "audio": "musics/telugu/Irumudi_Kattu.mp3"
    },
    {
        "id": 26,
        "title": "Jagadame",
        "artists": "Kunal Ganjawala",
        "movie": "Pokiri",
        "language": "telugu",
        "genre": "Mass",
        "year": 2006,
        "cover": "images/telugu/Jagadame.jpg",
        "audio": "musics/telugu/Jagadame.mp3"
    },
    {
        "id": 27,
        "title": "Jalsa Jalsa",
        "artists": "Baba Sehgal",
        "movie": "Jalsa",
        "language": "telugu",
        "genre": "Mass",
        "year": 2008,
        "cover": "images/telugu/Jalsa_Jalsa.jpg",
        "audio": "musics/telugu/Jalsa_Jalsa.mp3"
    },
    {
        "id": 28,
        "title": "Kalaavathi",
        "artists": "Sid Sriram",
        "movie": "Sarkaru Vaari Paata",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2022,
        "cover": "images/telugu/Kalaavathi.jpg",
        "audio": "musics/telugu/Kalaavathi.mp3"
    },
    {
        "id": 29,
        "title": "Kissik",
        "artists": "Sublahshini",
        "movie": "Pushpa 2: The Rule",
        "language": "telugu",
        "genre": "Dance",
        "year": 2024,
        "cover": "images/telugu/Kissik.jpg",
        "audio": "musics/telugu/Kissik.mp3"
    },
    {
        "id": 30,
        "title": "Kung Fu Kumaari",
        "artists": "Deepak, Ramya Behara",
        "movie": "Bruce Lee: The Fighter",
        "language": "telugu",
        "genre": "Mass",
        "year": 2015,
        "cover": "images/telugu/Kung_Fu_Kumaari.jpg",
        "audio": "musics/telugu/Kung_Fu_Kumaari.mp3"
    },
    {
        "id": 31,
        "title": "Kurchi Madathapetti",
        "artists": "Sahithi Chaganti, Sri Krishna",
        "movie": "Guntur Kaaram",
        "language": "telugu",
        "genre": "Mass",
        "year": 2024,
        "cover": "images/telugu/Kurchi_Madathapetti.jpg",
        "audio": "musics/telugu/Kurchi_Madathapetti.mp3"
    },
    {
        "id": 32,
        "title": "Mahanubhavudu",
        "artists": "M.M. Manasi, Geetha Madhuri",
        "movie": "Mahanubhavudu",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2017,
        "cover": "images/telugu/Mahanubhavudu.jpg",
        "audio": "musics/telugu/Mahanubhavudu.mp3"
    },
    {
        "id": 33,
        "title": "Mallepoola Pallaki",
        "artists": "Dappu Srinu",
        "movie": "Irumudi",
        "language": "telugu",
        "genre": "Devotional",
        "year": 2026,
        "cover": "images/telugu/Mallepoola_Pallaki.jpg",
        "audio": "musics/telugu/Mallepoola_Pallaki.mp3"
    },
    {
        "id": 34,
        "title": "Mawaa Enthaina",
        "artists": "Thaman S, Sri Krishna, Ramachari, Rahul Sipligunj",
        "movie": "Guntur Kaaram",
        "language": "telugu",
        "genre": "Mass",
        "year": 2024,
        "cover": "images/telugu/Mawaa_Enthaina.jpg",
        "audio": "musics/telugu/Mawaa_Enthaina.mp3"
    },
    {
        "id": 35,
        "title": "Mira Mira Meesam",
        "artists": "Anurag Kulkarni",
        "movie": "Katamarayudu",
        "language": "telugu",
        "genre": "Mass",
        "year": 2017,
        "cover": "images/telugu/Mira_Mira_Meesam.jpg",
        "audio": "musics/telugu/Mira_Mira_Meesam.mp3"
    },
    {
        "id": 36,
        "title": "Nattu Nattu",
        "artists": "Rahul Sipligunj, Kaala Bhairava",
        "movie": "RRR",
        "language": "telugu",
        "genre": "Dance",
        "year": 2022,
        "cover": "images/telugu/Nattu_Nattu.jpg",
        "audio": "musics/telugu/Nattu_Nattu.mp3"
    },
    {
        "id": 37,
        "title": "Nee Dookudu",
        "artists": "Shankar Mahadevan",
        "movie": "Dookudu",
        "language": "telugu",
        "genre": "Mass",
        "year": 2011,
        "cover": "images/telugu/Nee_Dookudu.jpg",
        "audio": "musics/telugu/Nee_Dookudu.mp3"
    },
    {
        "id": 38,
        "title": "Odiyamma",
        "artists": "Dhruv Vikram, Shruti Haasan, Chinmayi",
        "movie": "Hi Nanna",
        "language": "telugu",
        "genre": "Dance",
        "year": 2023,
        "cover": "images/telugu/Odiyamma.jpg",
        "audio": "musics/telugu/Odiyamma.mp3"
    },
    {
        "id": 39,
        "title": "Oo Antava Oo Oo Antava",
        "artists": "Indravathi Chauhan",
        "movie": "Pushpa: The Rise",
        "language": "telugu",
        "genre": "Dance",
        "year": 2021,
        "cover": "images/telugu/Oo_Antava_Oo_Oo_Antava.jpg",
        "audio": "musics/telugu/Oo_Antava_Oo_Oo_Antava.mp3"
    },
    {
        "id": 40,
        "title": "Pacha Bottasi",
        "artists": "Karthik, Damini",
        "movie": "Baahubali: The Beginning",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2015,
        "cover": "images/telugu/Pacha_Bottasi.jpg",
        "audio": "musics/telugu/Pacha_Bottasi.mp3"
    },
    {
        "id": 41,
        "title": "Peelings",
        "artists": "Shankar Babu Kandukoori, Laxmi Dasa",
        "movie": "Pushpa 2: The Rule",
        "language": "telugu",
        "genre": "Dance",
        "year": 2024,
        "cover": "images/telugu/Peelings.jpg",
        "audio": "musics/telugu/Peelings.mp3"
    },
    {
        "id": 42,
        "title": "Pilla Chao",
        "artists": "Rahul Nambiar",
        "movie": "Businessman",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2011,
        "cover": "images/telugu/Pilla_Chao.jpg",
        "audio": "musics/telugu/Pilla_Chao.mp3"
    },
    {
        "id": 43,
        "title": "Raavanaa Sandanaala",
        "artists": "Kareemullah",
        "movie": "Lenin",
        "language": "telugu",
        "genre": "Mass",
        "year": 2026,
        "cover": "images/telugu/Raavanaa_Sandanaala.jpg",
        "audio": "musics/telugu/Raavanaa_Sandanaala.mp3"
    },
    {
        "id": 44,
        "title": "Ramana Aei",
        "artists": "Mano, Swarnalatha",
        "movie": "Guntur Kaaram",
        "language": "telugu",
        "genre": "Mass",
        "year": 2024,
        "cover": "images/telugu/Ramana_Aei.jpg",
        "audio": "musics/telugu/Ramana_Aei.mp3"
    },
    {
        "id": 45,
        "title": "Ranga Ranga Rangasthalaana",
        "artists": "Rahul Sipligunj",
        "movie": "Rangasthalam",
        "language": "telugu",
        "genre": "Mass",
        "year": 2018,
        "cover": "images/telugu/Ranga_Ranga_Rangasthalaana.jpg",
        "audio": "musics/telugu/Ranga_Ranga_Rangasthalaana.mp3"
    },
    {
        "id": 46,
        "title": "Rebel Saab",
        "artists": "Sanjith Hegde, Blaaze",
        "movie": "The RajaSaab",
        "language": "telugu",
        "genre": "Dance",
        "year": 2026,
        "cover": "images/telugu/Rebel_Saab.jpg",
        "audio": "musics/telugu/Rebel_Saab.mp3"
    },
    {
        "id": 47,
        "title": "Run",
        "artists": "Sai Sharan, Nivaz",
        "movie": "Bruce Lee - The Fighter",
        "language": "telugu",
        "genre": "Mass",
        "year": 2015,
        "cover": "images/telugu/Run.jpg",
        "audio": "musics/telugu/Run.mp3"
    },
    {
        "id": 48,
        "title": "Saahore Baahubali",
        "artists": "Mounima,Daler Mehndi",
        "movie": "Baahubali 2: The Conclusion",
        "language": "telugu",
        "genre": "Epic",
        "year": 2017,
        "cover": "images/telugu/Saahore_Baahubali.jpg",
        "audio": "musics/telugu/Saahore_Baahubali.mp3"
    },
    {
        "id": 49,
        "title": "Samajavaragamana",
        "artists": "Sid Sriram",
        "movie": "Ala Vaikunthapurramuloo",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2020,
        "cover": "images/telugu/Samajavaragamana.jpg",
        "audio": "musics/telugu/Samajavaragamana.mp3"
    },
    {
        "id": 50,
        "title": "Samayama",
        "artists": "Anurag Kulkarni, Sithara Krishnakumar",
        "movie": "Hi Nanna",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2023,
        "cover": "images/telugu/Samayama.jpg",
        "audio": "musics/telugu/Samayama.mp3"
    },
    {
        "id": 51,
        "title": "Sathyameva Jayathe",
        "artists": "Shankar Mahadevan, Prudhvi Chandra,Thaman S",
        "movie": "Vakeel Saab",
        "language": "telugu",
        "genre": "Inspirational",
        "year": 2021,
        "cover": "images/telugu/Sathyameva_Jayathe.jpg",
        "audio": "musics/telugu/Sathyameva_Jayathe.mp3"
    },
    {
        "id": 52,
        "title": "Sir Osthara",
        "artists": "Suchitra, Thaman S",
        "movie": "Businessman",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2011,
        "cover": "images/telugu/Sir_Osthara.jpg",
        "audio": "musics/telugu/Sir_Osthara.mp3"
    },
    {
        "id": 53,
        "title": "The Rage Of Daaku",
        "artists": "Nakash Aziz, Bharath Raj, Ritesh G Rao, K. Pranati",
        "movie": "Daaku Maharaaj",
        "language": "telugu",
        "genre": "Mass",
        "year": 2024,
        "cover": "images/telugu/The_Rage_Of_Daaku.jpg",
        "audio": "musics/telugu/The_Rage_Of_Daaku.mp3"
    },
    {
        "id": 54,
        "title": "Tillu Square Revamp",
        "artists": "Ram Miriyala",
        "movie": "Tillu Square",
        "language": "telugu",
        "genre": "Mass",
        "year": 2024,
        "cover": "images/telugu/Tillu_Square_Revamp.jpg",
        "audio": "musics/telugu/Tillu_Square_Revamp.mp3"
    },
    {
        "id": 55,
        "title": "Vaarevaa Vaarevaa",
        "artists": "Shweta Mohan, Jubin Nautiyal",
        "movie": "Lenin",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2026,
        "cover": "images/telugu/Vaarevaa_Vaarevaa.jpg",
        "audio": "musics/telugu/Vaarevaa_Vaarevaa.mp3"
    },
    {
        "id": 56,
        "title": "Who Are You",
        "artists": "Devi Sri Prasad",
        "movie": "1: Nenokkadine",
        "language": "telugu",
        "genre": "Mass",
        "year": 2014,
        "cover": "images/telugu/Who_Are_You.jpg",
        "audio": "musics/telugu/Who_Are_You.mp3"
    },
    {
        "id": 57,
        "title": "Yeshanagula",
        "artists": "Prabha Bangarigalla, Addula Jangireddy",
        "movie": "The Paradise",
        "language": "telugu",
        "genre": "Folk",
        "year": 2026,
        "cover": "images/telugu/Yeshanagula.jpg",
        "audio": "musics/telugu/Yeshanagula.mp3"
    },
    {
        "id": 58,
        "title": "Yetta Yetta",
        "artists": "Sri Krishna, Bhaskara Bhatla",
        "movie": "Lenin",
        "language": "telugu",
        "genre": "Romantic",
        "year": 2026,
        "cover": "images/telugu/Yetta_Yetta.jpg",
        "audio": "musics/telugu/Yetta_Yetta.mp3"
    },
    {
        "id": 59,
        "title": "Coolie Disco",
        "artists": "Anirudh Ravichander",
        "movie": "Coolie",
        "language": "tamil",
        "genre": "Dance",
        "year": 2025,
        "cover": "images/tamil/Coolie_Disco.jpg",
        "audio": "musics/tamil/Coolie_Disco.mp3"
    },
    {
        "id": 60,
        "title": "I Am The Danger",
        "artists": "Siddharth Basrur, Anirudh Ravichander",
        "movie": "Coolie",
        "language": "tamil",
        "genre": "Mass",
        "year": 2025,
        "cover": "images/tamil/I_Am_The_Danger.jpg",
        "audio": "musics/tamil/I_Am_The_Danger.mp3"
    },
    {
        "id": 61,
        "title": "Monica",
        "artists": "Sublahshini, Anirudh Ravichander, Asal Kolaar",
        "movie": "Coolie",
        "language": "tamil",
        "genre": "Dance",
        "year": 2025,
        "cover": "images/tamil/Monica.jpg",
        "audio": "musics/tamil/Monica.mp3"
    },
    {
        "id": 62,
        "title": "Neno Butterfly",
        "artists": "Sublahshini",
        "movie": "Vishwanath & Sons",
        "language": "tamil",
        "genre": "Romantic",
        "year": 2026,
        "cover": "images/tamil/Neno_Butterfly.jpg",
        "audio": "musics/tamil/Neno_Butterfly.mp3"
    },
    {
        "id": 63,
        "title": "Pavazha Malli",
        "artists": "Sai Abhyankkar, Shruti Haasan",
        "movie": null,
        "language": "tamil",
        "genre": "Romantic",
        "year": 2026,
        "cover": "images/tamil/Pavazha_Malli.jpg",
        "audio": "musics/tamil/Pavazha_Malli.mp3"
    },
    {
        "id": 64,
        "title": "Powerhouse",
        "artists": "Anirudh Ravichander, Arivu",
        "movie": "Coolie",
        "language": "tamil",
        "genre": "Mass",
        "year": 2025,
        "cover": "images/tamil/Powerhouse.jpg",
        "audio": "musics/tamil/Powerhouse.mp3"
    },
    {
        "id": 65,
        "title": "Raga Of Revenge",
        "artists": "Anirudh Ravichander",
        "movie": "DC",
        "language": "tamil",
        "genre": "Mass",
        "year": 2026,
        "cover": "images/tamil/Raga_Of_Revenge.jpg",
        "audio": "musics/tamil/Raga_Of_Revenge.mp3"
    },
    {
        "id": 66,
        "title": "Aari Aari",
        "artists": "Navtej Singh Rehal, Shashwat Sachdev, Khan Saab, Jasmine Sandlas, Sudhir Yaduvanshi",
        "movie": "Dhurandhar: The Revenge",
        "language": "hindi",
        "genre": "Mass",
        "year": 2026,
        "cover": "images/hindi/Aari_Aari.jpg",
        "audio": "musics/hindi/Aari_Aari.mp3"
    },
    {
        "id": 67,
        "title": "Believer",
        "artists": "Imagine Dragons",
        "movie": null,
        "language": "international",
        "genre": "Rock",
        "year": 2017,
        "cover": "images/international/Believer.jpg",
        "audio": "musics/international/Believer.mp3"
    },
    {
        "id": 68,
        "title": "Bones",
        "artists": "Imagine Dragons",
        "movie": null,
        "language": "international",
        "genre": "Rock",
        "year": 2022,
        "cover": "images/international/Bones.jpg",
        "audio": "musics/international/Bones.mp3"
    },
    {
        "id": 69,
        "title": "Im Unstoppable Today",
        "artists": "Sia",
        "movie": null,
        "language": "international",
        "genre": "Pop",
        "year": 2016,
        "cover": "images/international/Im_Unstoppable_Today.jpg",
        "audio": "musics/international/Im_Unstoppable_Today.mp3"
    },
    {
        "id": 70,
        "title": "On The Floor",
        "artists": "Jennifer Lopez, Pitbull",
        "movie": null,
        "language": "international",
        "genre": "Dance",
        "year": 2011,
        "cover": "images/international/On_The_Floor.jpg",
        "audio": "musics/international/On_The_Floor.mp3"
    }
];